services:
    INSERT_SERVICE_NAME:
        build:
            context: .
            dockerfile: ./INSERT_DOCKERFILE_PATH
        image: INSERT_IMAGE_NAME:INSERT_IMAGE_TAG
        restart: unless-stopped
        container_name: INSERT_CONTANER_NAME
        ports:
            - 'INSERT_MAIN_HTTP_PORT:INSERT_MAIN_HTTP_PORT'
            - 'INSERT_MAIN_HTTPS_PORT:INSERT_MAIN_HTTPS_PORT'
            - 'INSERT_API_HTTP_PORT:INSERT_API_HTTP_PORT'
            - 'INSERT_API_HTTPS_PORT:INSERT_API_HTTPS_PORT'
            - 'INSERT_KONG_GATEWAY_HTTP_PORT:INSERT_KONG_GATEWAY_HTTP_PORT'
            - 'INSERT_KONG_GATEWAY_HTTPS_PORT:INSERT_KONG_GATEWAY_HTTPS_PORT'
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            - KONG_PG_PORT=INSERT_POSTGRES_INSTANCE_PORT
            - KONG_PG_SSL=on
            - KONG_PG_SSL_VERIFY=off
            - KONG_PROXY_LISTEN="0.0.0.0:INSERT_MAIN_HTTP_PORT, 0.0.0.0:INSERT_MAIN_HTTPS_PORT ssl"
            - KONG_DATABASE=postgres
            - KONG_ADMIN_LISTEN="0.0.0.0:INSERT_API_HTTP_PORT, 0.0.0.0:INSERT_API_HTTPS_PORT ssl"
            - KONG_ADMIN_GUI_LISTEN="0.0.0.0:INSERT_KONG_GATEWAY_HTTP_PORT, 0.0.0.0:INSERT_KONG_GATEWAY_HTTPS_PORT ssl"
            - KONG_AMMIN_GUI_URL="INSERT_KONG_DASHBOARD_ENDPOINT"
            - KONG_PG_HOST=INSERT_POSTGRE_KONG_GATEWAY_HOST
            - KONG_PG_USER=INSERT_POSTGRE_KONG_GATEWAY_USERNAME
            - KONG_PG_PASSWORD=INSERT_POSTGRE_KONG_GATEWAY_PASSWORD